### ISSUE TITLE
New error prevent tracked schemas to write into DB

### ISSUE THREAD

**Issue by bumbus** [ZennerIoT/ex_audit#93]
This happens while inserts and updates.
I wonder what wrong here, since this problem appeared this week.
You know how to fix this?

```
[error] GenServer #PID<0.960.0> terminating
** (FunctionClauseError) no function clause matching in Ecto.Repo.Schema.do_update/4
    (ecto 3.9.1) Ecto.Repo.Schema.do_update(MyApp.Repo, MyApp.Repo, #Ecto.Changeset<action: nil, changes: %{gender: "Female"}, errors: [], data: #MyApp.Accounts.User<>, valid?: true>, [ex_audit_custom: []])
    (ex_audit 0.9.0) lib/repo/schema.ex:30: anonymous fn/4 in ExAudit.Schema.update/4
    (ex_audit 0.9.0) lib/repo/schema.ex:155: ExAudit.Schema.run_in_multi/4
    (ecto 3.9.1) lib/ecto/multi.ex:801: Ecto.Multi.apply_operation/5
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.9.1) lib/ecto/multi.ex:775: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:1190: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
    (ecto 3.9.1) lib/ecto/repo/transaction.ex:18: Ecto.Repo.Transaction.transaction/4
    (ex_audit 0.9.0) lib/repo/schema.ex:146: ExAudit.Schema.augment_transaction/3
    ````

**Comment by narrowtux** [comment]
fixed by merged PR
