### ISSUE TITLE
Using ex_audit breaks `returning` option for Repo functions

### ISSUE THREAD

**Issue by willus10245** [ZennerIoT/ex_audit#95]
The insert and update functions in Ecto accept a `returning` option to specify specific fields to return after the operation. Passing this option to an ExAudit repo results in the following error. 

```
** (KeyError) key :access_id not found in: %{action: {:action, ExAudit.Type.Action}, entity_id: {:entity_id, :integer}, entity_schema: {:entity_schema, ExAudit.Type.Schema}, id: {:id, :id}, patch: {:patch, ExAudit.Type.Patch}, recorded_at: {:recorded_at, :utc_datetime}, rollback: {:rollback, :boolean}, user_id: {:user_id, :id}}
    :erlang.map_get(:access_id, %{action: {:action, ExAudit.Type.Action}, entity_id: {:entity_id, :integer}, entity_schema: {:entity_schema, ExAudit.Type.Schema}, id: {:id, :id}, patch: {:patch, ExAudit.Type.Patch}, recorded_at: {:recorded_at, :utc_datetime}, rollback: {:rollback, :boolean}, user_id: {:user_id, :id}})
    (ecto 3.10.0) lib/ecto/repo/schema.ex:611: anonymous fn/3 in Ecto.Repo.Schema.fields_to_sources/2
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.10.0) lib/ecto/repo/schema.ex:45: Ecto.Repo.Schema.do_insert_all/7
    (ex_audit 0.10.0) lib/repo/schema.ex:16: anonymous fn/5 in ExAudit.Schema.insert/4
    (ex_audit 0.10.0) lib/repo/schema.ex:155: ExAudit.Schema.run_in_multi/4
    (ecto 3.10.0) lib/ecto/multi.ex:832: Ecto.Multi.apply_operation/5
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.10.0) lib/ecto/multi.ex:806: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.10.0) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
    (ecto 3.10.0) lib/ecto/repo/transaction.ex:18: Ecto.Repo.Transaction.transaction/4
    (ex_audit 0.10.0) lib/repo/schema.ex:146: ExAudit.Schema.augment_transaction/3
```

**Comment by narrowtux** [comment]
the `returning` option is kind of unsupported in ex_audit since that's what it's using internally to get the actual changes. 

Ecto set's the returning option to `true` by default, if it's set to anything else, ex_audit won't be able to track the changes.
